/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SholatRouteImport } from './routes/sholat'
import { Route as PuasaRouteImport } from './routes/puasa'
import { Route as PengeluaranRouteImport } from './routes/pengeluaran'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as MakanRouteImport } from './routes/makan'
import { Route as MabarRouteImport } from './routes/mabar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HaidRouteImport } from './routes/haid'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MabarIdRouteImport } from './routes/mabar.$id'

const SholatRoute = SholatRouteImport.update({
  id: '/sholat',
  path: '/sholat',
  getParentRoute: () => rootRouteImport,
} as any)
const PuasaRoute = PuasaRouteImport.update({
  id: '/puasa',
  path: '/puasa',
  getParentRoute: () => rootRouteImport,
} as any)
const PengeluaranRoute = PengeluaranRouteImport.update({
  id: '/pengeluaran',
  path: '/pengeluaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const MakanRoute = MakanRouteImport.update({
  id: '/makan',
  path: '/makan',
  getParentRoute: () => rootRouteImport,
} as any)
const MabarRoute = MabarRouteImport.update({
  id: '/mabar',
  path: '/mabar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HaidRoute = HaidRouteImport.update({
  id: '/haid',
  path: '/haid',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MabarIdRoute = MabarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MabarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/haid': typeof HaidRoute
  '/login': typeof LoginRoute
  '/mabar': typeof MabarRouteWithChildren
  '/makan': typeof MakanRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/puasa': typeof PuasaRoute
  '/sholat': typeof SholatRoute
  '/mabar/$id': typeof MabarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/haid': typeof HaidRoute
  '/login': typeof LoginRoute
  '/mabar': typeof MabarRouteWithChildren
  '/makan': typeof MakanRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/puasa': typeof PuasaRoute
  '/sholat': typeof SholatRoute
  '/mabar/$id': typeof MabarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/haid': typeof HaidRoute
  '/login': typeof LoginRoute
  '/mabar': typeof MabarRouteWithChildren
  '/makan': typeof MakanRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/puasa': typeof PuasaRoute
  '/sholat': typeof SholatRoute
  '/mabar/$id': typeof MabarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/haid'
    | '/login'
    | '/mabar'
    | '/makan'
    | '/pengaturan'
    | '/pengeluaran'
    | '/puasa'
    | '/sholat'
    | '/mabar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/haid'
    | '/login'
    | '/mabar'
    | '/makan'
    | '/pengaturan'
    | '/pengeluaran'
    | '/puasa'
    | '/sholat'
    | '/mabar/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/haid'
    | '/login'
    | '/mabar'
    | '/makan'
    | '/pengaturan'
    | '/pengeluaran'
    | '/puasa'
    | '/sholat'
    | '/mabar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  HaidRoute: typeof HaidRoute
  LoginRoute: typeof LoginRoute
  MabarRoute: typeof MabarRouteWithChildren
  MakanRoute: typeof MakanRoute
  PengaturanRoute: typeof PengaturanRoute
  PengeluaranRoute: typeof PengeluaranRoute
  PuasaRoute: typeof PuasaRoute
  SholatRoute: typeof SholatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sholat': {
      id: '/sholat'
      path: '/sholat'
      fullPath: '/sholat'
      preLoaderRoute: typeof SholatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puasa': {
      id: '/puasa'
      path: '/puasa'
      fullPath: '/puasa'
      preLoaderRoute: typeof PuasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengeluaran': {
      id: '/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/pengeluaran'
      preLoaderRoute: typeof PengeluaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makan': {
      id: '/makan'
      path: '/makan'
      fullPath: '/makan'
      preLoaderRoute: typeof MakanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mabar': {
      id: '/mabar'
      path: '/mabar'
      fullPath: '/mabar'
      preLoaderRoute: typeof MabarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haid': {
      id: '/haid'
      path: '/haid'
      fullPath: '/haid'
      preLoaderRoute: typeof HaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mabar/$id': {
      id: '/mabar/$id'
      path: '/$id'
      fullPath: '/mabar/$id'
      preLoaderRoute: typeof MabarIdRouteImport
      parentRoute: typeof MabarRoute
    }
  }
}

interface MabarRouteChildren {
  MabarIdRoute: typeof MabarIdRoute
}

const MabarRouteChildren: MabarRouteChildren = {
  MabarIdRoute: MabarIdRoute,
}

const MabarRouteWithChildren = MabarRoute._addFileChildren(MabarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  HaidRoute: HaidRoute,
  LoginRoute: LoginRoute,
  MabarRoute: MabarRouteWithChildren,
  MakanRoute: MakanRoute,
  PengaturanRoute: PengaturanRoute,
  PengeluaranRoute: PengeluaranRoute,
  PuasaRoute: PuasaRoute,
  SholatRoute: SholatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
